# MLTON
# =====
#
all:
	mkdir -p build && mlton -output build/lingua-000 lingua-000.mlb

run:
	@./build/lingua-000

# SMLNJ
# =====
#
# all:
# 	mkdir -p build && ml-build sources.cm Main.main build/lingua-000
#
# run:
# 	@sml @SMLload build/lingua-000.x86-darwin

clean:
	rm -rf ./build
